# root/root for user/password
services:
  db:
    image: mariadb:lts-ubi9
    container_name: mariadb
    environment:
      MARIADB_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - /opt/db/mariadb-data:/var/lib/mysql

  adminer:
    image: adminer
    container_name: adminer
    ports:
      - "8080:8080"
    environment:
      ADMINER_DEFAULT_SERVER: mariadb
    depends_on:
      - db
