{
 "title": "by endpoint",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "endpoint",
    "label": "endpoint",
    "query": {
     "query": "label_values(wt_request_duration_seconds_count,endpoint)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Request counts & rates", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Requests for $endpoint",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "increase(wt_requests_total{endpoint=\"$endpoint\"}[$__rate_interval])",
     "legendFormat": "$endpoint"
    }
   ]
  },
  {
   "title": "Requests per second for $endpoint",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "rate(wt_requests_total{endpoint=\"$endpoint\"}[$__rate_interval])",
     "legendFormat": "$endpoint"
    }
   ]
  },
  { "title": "Request durations", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Request durations for $endpoint (tooltip \"Value\" is  # of reqs)",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 14, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "sum by (le) (increase(wt_request_duration_seconds_bucket{endpoint=\"$endpoint\"}[$__rate_interval])) ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "50th & 95th percentile request durations for $endpoint",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, rate(wt_request_duration_seconds_bucket{endpoint=\"$endpoint\"}[$__rate_interval]))",
     "legendFormat": "95th"
    },
    {
     "expr": "histogram_quantile(0.50, rate(wt_request_duration_seconds_bucket{endpoint=\"$endpoint\"}[$__rate_interval]))",
     "legendFormat": "50th"
    }
   ]
  },
  {
   "title": "Avgerage request durations for $endpoint by status code",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by(status_code,endpoint)(rate(wt_request_duration_summary_seconds_sum{endpoint=\"$endpoint\"}[$__rate_interval]))\r\n/\r\nsum by(status_code,endpoint)(rate(wt_request_duration_summary_seconds_count{endpoint=\"$endpoint\"}[$__rate_interval]))\r\n",
     "legendFormat": "{{status_code}}"
    }
   ]
  }
 ]
}