{
 "title": "by resource ID",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "resource_id",
    "label": "resource ID",
    "query": {
     "query": "label_values(wt_resource_requests_total,resource_id)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Requests per resource ID",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum without(endpoint)(increase(wt_resource_requests_total[$__rate_interval]))\r\n",
     "legendFormat": "{{resource_id}}"
    }
   ]
  },
  {
   "title": "Last request per resource ID",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIsoNoDateIfToday" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "wt_last_request_time_seconds * 1000",
     "legendFormat": "{{resource_id}}"
    },
    {
     "expr": "wt_last_request_time_seconds * 1000",
     "legendFormat": "{{resource_id}}"
    }
   ]
  },
  {
   "title": "Last response per resource ID",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 17, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIsoNoDateIfToday" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "wt_last_response_time_seconds * 1000",
     "legendFormat": "{{resource_id}}"
    },
    {
     "expr": "wt_last_response_time_seconds * 1000",
     "legendFormat": "{{resource_id}}"
    }
   ]
  },
  {
   "title": "Pending requests by resource ID",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 11, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "wt_pending_requests", "legendFormat": "{{resource_id}}" }
   ]
  },
  {
   "title": "Pending requests by resource ID",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 11, "y": 8 },
   "targets": [
    { "expr": "wt_pending_requests", "legendFormat": "{{resource_id}}" }
   ]
  },
  {
   "title": "In progress requests by resource ID",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 11, "x": 0, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "wt_in_progress_requests", "legendFormat": "{{resource_id}}" }
   ]
  },
  {
   "title": "In progress requests by resource ID",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 11, "y": 13 },
   "targets": [
    { "expr": "wt_in_progress_requests", "legendFormat": "{{resource_id}}" }
   ]
  },
  { "title": "Request slots", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Request slot acquire durations (tooltip \"Value\" is  # of slots acquired)",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "sum by(le) (increase(wt_request_slot_acquire_duration_seconds_bucket[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request slot acquire errors per resource ID and error type",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 11, "y": 19 },
   "targets": [
    {
     "expr": "increase(wt_request_slot_errors_total[$__rate_interval])",
     "legendFormat": "{{resource_id}} - {{error_type}}"
    }
   ]
  },
  {
   "title": "Request slot acquire durations for $resource_id (tooltip \"Value\" is  # of slots acquired)",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 17, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "sum by(le) (increase(wt_request_slot_acquire_duration_seconds_bucket{resource_id=\"$resource_id\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Database pools and connections", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "Open DB connections by resource ID",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 10, "x": 0, "y": 36 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "wt_open_connections", "legendFormat": "{{resource_id}}" }
   ]
  },
  {
   "title": "Open DB connections",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 11, "x": 10, "y": 36 },
   "targets": [
    { "expr": "wt_open_connections", "legendFormat": "{{resource_id}}" }
   ]
  },
  {
   "title": "Pooled DB connections by resource ID",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 10, "x": 0, "y": 41 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "wt_pooled_connections", "legendFormat": "{{resource_id}}" }
   ]
  },
  {
   "title": "Pooled DB connections",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 11, "x": 10, "y": 41 },
   "targets": [
    { "expr": "wt_pooled_connections", "legendFormat": "{{resource_id}}" }
   ]
  },
  {
   "title": "Pool empty per resource ID",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 10, "x": 0, "y": 46 },
   "targets": [
    {
     "expr": "increase(wt_pool_empty_total[$__rate_interval])",
     "legendFormat": "{{resource_id}}"
    }
   ]
  },
  {
   "title": "Pool exhausted per resource ID",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 11, "x": 10, "y": 46 },
   "targets": [
    {
     "expr": "increase(wt_pool_exhausted_total[$__rate_interval])",
     "legendFormat": "{{resource_id}}"
    }
   ]
  },
  {
   "title": "DB connections created per resource ID",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 10, "x": 0, "y": 51 },
   "targets": [
    {
     "expr": "increase(wt_created_connections_total[$__rate_interval])",
     "legendFormat": "{{resource_id}}"
    }
   ]
  },
  {
   "title": "DB connection creation errors per resource ID",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 11, "x": 10, "y": 51 },
   "targets": [
    {
     "expr": "increase(wt_conn_creation_errors_total[$__rate_interval])",
     "legendFormat": "{{resource_id}} - {{error_type}}"
    }
   ]
  },
  {
   "title": "DB connections closed per resource ID",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 10, "x": 0, "y": 56 },
   "targets": [
    {
     "expr": "increase(wt_closed_connections_total[$__rate_interval])",
     "legendFormat": "{{resource_id}}"
    }
   ]
  },
  {
   "title": "Last connection created per resource ID",
   "type": "stat",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIsoNoDateIfToday" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "wt_last_conn_created_time_seconds * 1000",
     "legendFormat": "{{resource_id}}"
    },
    {
     "expr": "wt_last_conn_created_time_seconds * 1000",
     "legendFormat": "{{resource_id}}"
    }
   ]
  },
  {
   "title": "Last connection creation error per resource ID",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 7, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIsoNoDateIfToday" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "wt_last_conn_created_error_time_seconds * 1000",
     "legendFormat": "{{resource_id}}"
    },
    {
     "expr": "wt_last_conn_created_error_time_seconds * 1000",
     "legendFormat": "{{resource_id}}"
    }
   ]
  },
  {
   "title": "DB connection acquire durations (tooltip \"Value\" is  # of conns acquired)",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 67 },
   "targets": [
    {
     "expr": "sum by(le) (increase(wt_acquire_connection_duration_seconds_bucket[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DB connection acquire timeout errors per resource ID",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 12, "y": 67 },
   "targets": [
    {
     "expr": "increase(wt_conn_acquire_errors_total[$__rate_interval])",
     "legendFormat": "{{resource_id}}"
    }
   ]
  },
  {
   "title": "DB connection acquire duration for $resource_id (tooltip \"Value\" is  # of conns acquired)",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 75 },
   "targets": [
    {
     "expr": "sum by(le) (increase(wt_acquire_connection_duration_seconds_bucket{resource_id=\"$resource_id\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "DB connection usage durations", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 83 } },
  {
   "title": "DB connection usage duration for $resource_id (tooltip \"Value\" is  # of conns used)",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 84 },
   "targets": [
    {
     "expr": "sum by (le) (increase(wt_connection_usage_duration_seconds_bucket{resource_id=\"$resource_id\"}[$__rate_interval])) ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "50th & 95th percentile DB connection usage durations for $resource_id",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 92 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, rate(wt_connection_usage_duration_seconds_bucket{resource_id=\"$resource_id\"}[$__rate_interval]))",
     "legendFormat": "95th"
    },
    {
     "expr": "histogram_quantile(0.50, rate(wt_connection_usage_duration_seconds_bucket{resource_id=\"$resource_id\"}[$__rate_interval]))",
     "legendFormat": "50th"
    }
   ]
  },
  {
   "title": "Avg DB connection usage durations for $resource_id",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 12, "y": 92 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by(resource_id)(rate(wt_connection_usage_duration_seconds_sum{resource_id=\"$resource_id\"}[$__rate_interval]))\r\n/\r\nsum by(resource_id)(rate(wt_connection_usage_duration_seconds_count{resource_id=\"$resource_id\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Queries", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 100 } },
  {
   "title": "Queries per resource ID",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 101 },
   "targets": [
    {
     "expr": "increase(wt_queries_total[$__rate_interval])",
     "legendFormat": "{{resource_id}}"
    }
   ]
  },
  {
   "title": "Query errors per resource ID and error type",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 12, "y": 101 },
   "targets": [
    {
     "expr": "increase(wt_query_errors_total[$__rate_interval])",
     "legendFormat": "{{resource_id}} - {{error_type}}"
    }
   ]
  },
  {
   "title": "Query durations for $resource_id (tooltip \"Value\" is  # of queries)",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 15, "x": 0, "y": 109 },
   "targets": [
    {
     "expr": "sum by(le) (increase(wt_query_duration_seconds_bucket{resource_id=\"$resource_id\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "50th & 95th percentile query durations for $resource_id",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 117 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, rate(wt_query_duration_seconds_bucket{resource_id=\"$resource_id\"}[$__rate_interval]))",
     "legendFormat": "95th"
    },
    {
     "expr": "histogram_quantile(0.50, rate(wt_query_duration_seconds_bucket{resource_id=\"$resource_id\"}[$__rate_interval]))",
     "legendFormat": "50th"
    }
   ]
  },
  {
   "title": "Avg query durations for $resource_id",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 12, "y": 117 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by(resource_id)(rate(wt_query_duration_seconds_sum{resource_id=\"$resource_id\"}[$__rate_interval]))\r\n/\r\nsum by(resource_id)(rate(wt_query_duration_seconds_count{resource_id=\"$resource_id\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Query rows for $resource_id (tooltip \"Value\" is  # of queries, does not include streaming responses)",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 15, "x": 0, "y": 125 },
   "targets": [
    {
     "expr": "sum by(le) (increase(wt_query_rows_bucket{resource_id=\"$resource_id\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "50th & 95th percentile query rows for $resource_id, does not include streaming responses",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 133 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, rate(wt_query_rows_bucket{resource_id=\"$resource_id\"}[$__rate_interval]))",
     "legendFormat": "95th"
    },
    {
     "expr": "histogram_quantile(0.50, rate(wt_query_rows_bucket{resource_id=\"$resource_id\"}[$__rate_interval]))",
     "legendFormat": "50th"
    }
   ]
  },
  {
   "title": "Avg query rows for $resource_id, does not include streaming responses",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 12, "y": 133 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(resource_id)(rate(wt_query_rows_sum{resource_id=\"$resource_id\"}[$__rate_interval]))\r\n/\r\nsum by(resource_id)(rate(wt_query_rows_count{resource_id=\"$resource_id\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}