{
 "title": "main",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Requests per URL",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "increase(wt_requests_total[$__rate_interval])",
     "legendFormat": "{{endpoint}}"
    }
   ]
  },
  {
   "title": "Requests per resource ID",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum without(endpoint)(increase(wt_resource_requests_total[$__rate_interval]))\r\n",
     "legendFormat": "{{resource_id}}"
    }
   ]
  },
  {
   "title": "Request durations (tooltip \"Value\" is  # of reqs)",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by (le) (increase(wt_request_duration_seconds_bucket[$__rate_interval])) ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Last response per resource ID",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIsoNoDateIfToday" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "wt_last_response_time_seconds * 1000",
     "legendFormat": "{{resource_id}}"
    },
    {
     "expr": "wt_last_response_time_seconds * 1000",
     "legendFormat": "{{resource_id}}"
    }
   ]
  },
  {
   "title": "Responses by status codes",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "sum without(endpoint)(increase(wt_request_duration_summary_seconds_count[$__rate_interval]))",
     "legendFormat": "{{status_code}}"
    }
   ]
  },
  {
   "title": "Last request per resource ID",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIsoNoDateIfToday" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "wt_last_request_time_seconds * 1000",
     "legendFormat": "{{resource_id}}"
    },
    {
     "expr": "wt_last_request_time_seconds * 1000",
     "legendFormat": "{{resource_id}}"
    }
   ]
  },
  {
   "title": "Pending requests by resource ID",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 10, "x": 0, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "wt_pending_requests", "legendFormat": "{{resource_id}}" }
   ]
  },
  {
   "title": "In progress requests by resource ID",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 10, "x": 10, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "wt_in_progress_requests", "legendFormat": "{{resource_id}}" }
   ]
  },
  {
   "title": "Pending requests by resource ID",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 10, "x": 0, "y": 26 },
   "targets": [
    { "expr": "wt_pending_requests", "legendFormat": "{{resource_id}}" }
   ]
  },
  {
   "title": "In progress requests by resource ID",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 10, "x": 10, "y": 26 },
   "targets": [
    { "expr": "wt_in_progress_requests", "legendFormat": "{{resource_id}}" }
   ]
  },
  { "title": "Process metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "Memory usage per pid",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 10, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    { "expr": "wt_mem_vms_bytes", "legendFormat": "vms - pid {{pid}}" },
    { "expr": "wt_mem_rss_bytes", "legendFormat": "rss - pid {{pid}}" },
    { "expr": "wt_mem_shared_bytes", "legendFormat": "shared - pid {{pid}}" }
   ]
  },
  {
   "title": "RSS memory usage per pid",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 10, "x": 10, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "wt_mem_percent", "legendFormat": "pid {{pid}}" }
   ]
  },
  {
   "title": "RSS memory usage per pid",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 10, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expr": "wt_mem_percent", "legendFormat": "pid {{pid}}" }
   ]
  },
  {
   "title": "CPU usage per pid",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 10, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "wt_cpu_usage", "legendFormat": "pid {{pid}}" }
   ]
  },
  {
   "title": "Open file descriptors per pid",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 10, "x": 10, "y": 43 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "wt_open_fds", "legendFormat": "pid {{pid}}" }
   ]
  },
  {
   "title": "CPU usage per pid",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expr": "wt_cpu_usage", "legendFormat": "pid {{pid}}" }
   ]
  },
  {
   "title": "Open file descriptors per pid",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 10, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "wt_open_fds", "legendFormat": "pid {{pid}}" }
   ]
  },
  {
   "title": "I/O per pid",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(wt_io_read_bytes_total[$__rate_interval])",
     "legendFormat": "read - pid {{pid}}"
    },
    {
     "expr": "rate(wt_io_write_bytes_total[$__rate_interval])",
     "legendFormat": "write - pid {{pid}}"
    }
   ]
  }
 ]
}